### ISSUE TITLE
Using ES modules

### ISSUE THREAD

**Issue by moltar** [suds-sky/aws-sdkv3-esbuild-treeshaking#1]
Btw, added this to tsconfig, and it helped to reduce the bundle too:

```
   "paths": {
      "@aws-sdk/*": [
        "../node_modules/@aws-sdk/*/dist-es",
        "../node_modules/@aws-sdk/*"
      ],
```

**Comment by suds-sky** [comment]
@moltar thanks for sharing it. I have already tried this in the project but didn't manage to get the bundle size lower. May be I am missing something. Please find below which I tried.

```
"@aws-sdk/*": [
    "node_modules/@aws-sdk/*/dist-es",
    "node_modules/@aws-sdk/*"
],
```

**Comment by moltar** [comment]
I think the issue is `node_modules/` vs `./node_modules/`.

I didn't know this either, but my IDE (VS Code) told me 😁 

> Path mapping to be computed relative to baseUrl option.

And if `baseUrl` is not explicitly set, I think it fails to find the paths to map to.

**Comment by moltar** [comment]
In my codebase I have `../`, because our `baseUrl` is set to `./src`.

**Comment by suds-sky** [comment]
Thanks for this, I use Webstrom and didn't get any error but there was a warning when we do `cdk synth` which I missed. Now the bundle size gone down 😹
